{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
    {{- include "proj_01_helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.port }}
      name: postgres
{{- end }}
